# Generated by Django 5.2.17 on 2026-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaFalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, help_text="'ip:<endereço>' ou 'tel:<telefone>'.", max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'tentativa falha',
                'verbose_name_plural': 'tentativas falhas',
            },
        ),
    ]
