# Generated by Django 5.2.17 on 2026-09-23 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('duracao_minutos', models.PositiveSmallIntegerField(help_text='Tempo do atendimento. É o tempo que o cliente vê.', validators=[django.core.validators.MinValueValidator(5)], verbose_name='duração (minutos)')),
                ('intervalo_minutos', models.PositiveSmallIntegerField(default=0, help_text='Tempo após o atendimento para higienização. Bloqueia a agenda, mas não aparece para o cliente.', verbose_name='intervalo (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'procedimento',
                'verbose_name_plural': 'procedimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'tipo de recurso',
                'verbose_name_plural': 'tipos de recurso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='catalogo.tiporecurso', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['tipo__nome', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nome'), name='recurso_nome_unico_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='catalogo.procedimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tiporecurso', verbose_name='tipo de recurso')),
            ],
            options={
                'verbose_name': 'recurso necessário',
                'verbose_name_plural': 'recursos necessários',
                'constraints': [models.UniqueConstraint(fields=('procedimento', 'tipo'), name='procedimento_tipo_recurso_unico')],
            },
        ),
    ]
