# Generated by Django 5.2.17 on 2026-09-23 01:05

import agenda.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        # Necessária para as exclusion constraints (igualdade + sobreposição de períodos)
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('telefone', models.CharField(help_text='Formato +5511999999999.', max_length=20, unique=True, verbose_name='telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('consentimento_em', models.DateTimeField(blank=True, null=True, verbose_name='consentimento LGPD em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(help_text='Fim do intervalo de higienização (início + duração + intervalo).', verbose_name='fim')),
                ('duracao_minutos', models.PositiveSmallIntegerField(verbose_name='duração (minutos)')),
                ('intervalo_minutos', models.PositiveSmallIntegerField(verbose_name='intervalo (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço (R$)')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('atendido', 'Atendido'), ('faltou', 'Faltou'), ('cancelado', 'Cancelado'), ('precisa_reagendar', 'Precisa reagendar')], default='agendado', max_length=20, verbose_name='status')),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('profissional', 'Profissional'), ('gerente', 'Gerente')], max_length=20, verbose_name='criado por')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelado_por', models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('profissional', 'Profissional'), ('gerente', 'Gerente')], max_length=20, verbose_name='cancelado por')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='catalogo.procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='equipe.profissional')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='agenda.agendamento')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='catalogo.recurso')),
            ],
            options={
                'verbose_name': 'recurso alocado',
                'verbose_name_plural': 'recursos alocados',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='recursos',
            field=models.ManyToManyField(blank=True, through='agenda.AgendamentoRecurso', to='catalogo.recurso'),
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(verbose_name='fim')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('profissional', models.ForeignKey(blank=True, help_text='Vazio = bloqueio geral da clínica (vale para todos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='equipe.profissional')),
            ],
            options={
                'verbose_name': 'bloqueio',
                'verbose_name_plural': 'bloqueios',
                'ordering': ['inicio'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.cliente'),
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('inicio', models.TimeField(verbose_name='início')),
                ('fim', models.TimeField(verbose_name='fim')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='equipe.profissional')),
            ],
            options={
                'verbose_name': 'horário de trabalho',
                'verbose_name_plural': 'horários de trabalho',
                'ordering': ['dia_semana', 'inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='agendamentorecurso',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(agenda.models.TsTzRange('inicio', 'fim', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('recurso', '=')], name='recurso_sem_sobreposicao'),
        ),
        migrations.AddConstraint(
            model_name='bloqueio',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='bloqueio_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendamento_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['agendado', 'atendido', 'faltou'])), expressions=[(agenda.models.TsTzRange('inicio', 'fim', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('profissional', '=')], name='agendamento_sem_sobreposicao_profissional'),
        ),
        migrations.AddConstraint(
            model_name='horariotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='horario_trabalho_fim_apos_inicio'),
        ),
    ]
