# Generated by Django 5.2.17 on 2026-09-23 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('procedimentos', models.ManyToManyField(blank=True, related_name='profissionais', to='catalogo.procedimento', verbose_name='procedimentos que realiza')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['nome'],
            },
        ),
    ]
