# Generated by Django 5.2.17 on 2026-09-23 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(default='Agendamento', max_length=100, verbose_name='nome da clínica')),
                ('grade_minutos', models.PositiveSmallIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (30, '30 min')], default=15, help_text='Espaçamento entre os horários oferecidos ao cliente.', verbose_name='grade de horários')),
                ('antecedencia_minima_horas', models.PositiveSmallIntegerField(default=2, help_text='Com quantas horas de antecedência, no mínimo, o cliente pode agendar.', verbose_name='antecedência mínima (horas)')),
                ('antecedencia_maxima_dias', models.PositiveSmallIntegerField(default=60, help_text='Até quantos dias à frente o cliente pode agendar.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='antecedência máxima (dias)')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configuração',
            },
        ),
        migrations.CreateModel(
            name='HorarioClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='dia da semana')),
                ('inicio', models.TimeField(verbose_name='abre às')),
                ('fim', models.TimeField(verbose_name='fecha às')),
            ],
            options={
                'verbose_name': 'horário da clínica',
                'verbose_name_plural': 'horários da clínica',
                'ordering': ['dia_semana'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='horario_clinica_fim_apos_inicio')],
            },
        ),
    ]
