# Generated by Django 5.2.17 on 2026-09-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_sequencia_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='foto_atualizada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='FotoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.BinaryField()),
                ('tipo', models.CharField(max_length=30, verbose_name='tipo de arquivo')),
                ('estabelecimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='clinica.estabelecimento')),
            ],
            options={
                'verbose_name': 'foto do estabelecimento',
                'verbose_name_plural': 'fotos dos estabelecimentos',
            },
        ),
    ]
